Update index.html
htmlacademy-htmlcss/1793357-device-32 pull request #2
Opened 2021-09-29 13:51 UTC by lolipopaa

Разметка главной страницы

2021-09-29 17:56 UTC, davletbaev requested changes
Привет, проверил твое задание.
Для начала ты очень неплохо научилась разделять макет на блоки и строить ~~практически~~ правильную структуру блоков. Это очень хорошо.
Есть моменты которые нужно доработать, но большинство из них небольшие, так что не пугайся количества комментариев)
В целом работа очень хорошая, молодец, что беспокоишься о доступности👍🏻

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +                                <input type="checkbox" name="black" checked>
Нужно добавить на input класс visually-hidden, так как ты будешь делать чекбокс через кастомную иконку.

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +                                <input type="checkbox" name="black" checked>
Так как все эти чекбоксы относятся к цвету, то будет правильнее сделать им всем одно имя, с указанием того, что оно может иметь несколько значений.
```html
<input type="checkbox" name="color[]" value="black" checked />
<input type="checkbox" name="color[]" value="white" />
<input type="checkbox" name="color[]" value="blue" checked />
```
Тогда при заполнении формы у тебя только одно поле color со списком отмеченных значений
```json
{
  "color": ["black", "white"]
}
```
Тогда как при твоей реализации будет отдельное поле для каждого цвета:
```json
{
  "black": true,
  "blue": false,
  "white": true
}
```
с этим будет не очень удобно работать на сервере.

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +                            <input type="radio" value="yes" name="Bluetooth-radio" checked>
Молодец, что использовала здесь одинаковое имя для радио-кнопок. 
Но старайся не использовать заглавные буквы в названиях полей. За это бэкендер тебе спасибо не скажет :)
Но скажет спасибо, если в значениях подобных радио-кнопок, где подразумевается просто значение да/нет, будешь использовать сразу 1/0, вместо yes/no. Так можно будет избежать лишних проверок и трансформаций значений.

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +        <section>
Здесь фильтр находится сбоку от основного контента страницы, и сам им не является по сути. Поэтому семантически более правильно будет использовать здесь тег aside. Как для сайдбара.

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +                <span class="sorting-up"></span>
Эти кнопочки по сути очень похожи на радио-кнопки. Ты сортируешь или по возрастанию или по убыванию. Нельзя сделать одновременную сортировку в обоих направлениях. Поэтому лучше их тоже включить в форму, и оформить радио-кнопками.

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +            <ul class="pagination-list">
Этот блок тоже считается навигацией, так что его тоже можно обернуть в nav

2021-09-29 17:56 UTC, davletbaev commented on catalog.html
> +                        ...
такие точки обычно не кликабельны в навигации, а просто подразумевают, что там еще есть страницы между

2021-09-30 16:15 UTC, lolipopaa commented on index.html
> +        <ul class="navigation-list navigation-user">
мне тоже кажется это логичным, но на лайве почему-то делали два списка
я не совсем понимаю, когда он один, а когда их нужно разделять

2021-09-30 16:27 UTC, lolipopaa commented on catalog.html
> +                    <button class="range-button min-range" type="button">
я не понимаю, как сделать эту линию
просто через <img> ?

2021-09-30 16:28 UTC, lolipopaa commented on catalog.html
> +                    <button class="range-button min-range" type="button">
<img>

2021-09-30 16:38 UTC, lolipopaa commented on catalog.html
> +                                <input type="checkbox" name="black" checked>
на счет visually-hidden: правильно ли я понимаю, я скрываю все инпуты с цветами в класс visually-hidden, а дальше в css добавляю им иконки? если да, то потом при нажатии на эти иконки, он сам поймет, к какому именно цвету они относятся?

2021-09-30 16:47 UTC, lolipopaa commented on catalog.html
> +                        <a href="#">
а это не через css нужно делать? 
или нужно добавить в каждый див с карточкой товара отдельный span, который уже будет задаваться в css?

2021-09-30 16:57 UTC, lolipopaa commented on index.html
> +        <article class="offers">
тут я совсем запуталась
тут будет div с фотографией, точками, описанием и кнопками, а как он будет переключаться?
и я все равно, не понимаю, почему не article. это же реклама, ее можно вывести на другой сайт и она не потеряется. или из-за того, что тут нет конкретики (например, указания компании или контактов), ее нельзя вынести отдельно?

2021-09-30 16:58 UTC, lolipopaa commented on index.html
> +                <h3>Доставка</h3>
и еще вопросик: а тут лучше делать с помощью id из-за джавы?

2021-10-01 11:15 UTC, davletbaev commented on index.html
> +        <ul class="navigation-list navigation-user">
Я не говорил объединить их в один список) 
Просто в nav у тебя обернут только один список, внеси в него второй список тоже.
Оба списка относятся к навигации. К тому же на лайве показывают лишь один из вариантов того, как можно сделать. Конечное решение все-таки остается за тобой)

2021-10-01 11:23 UTC, davletbaev commented on index.html
> +        <article class="offers">
Давай объясню подробнее.
Весь этот блок, это один слайдер.
<img width="678" alt="Снимок экрана 2021-10-01 в 14 16 04" src="https://user-images.githubusercontent.com/25131400/135611171-4cea966c-f4f4-4858-9ff9-a72b1c9a4879.png">
Слайдер состоит из нескольких элементов: навигация (стрелки), пагинация (точки), а также контейнер со слайдами.
Слайдов у тебя аж 3 штуки:
![image](https://user-images.githubusercontent.com/25131400/135611384-1fb7c329-57d5-4800-8999-4dbe5486e106.png)
Заголовок, картинка, текст и кнопка относятся к каждому конкретному слайду и на каждой слайде они свои.
Стрелки и точки относятся к слайдеру в целом, их не надо дублировать в каждом слайде, они лежат как бы поверх него.
Если схематично то примерная разметка будет такая
```html
<div class="slider">
  <div class="slider-container">
    <article class="slide is-selected">...</article>
    <article class="slide">...</article>
    <article class="slide">...</article>
  </div>

  <div class="slider-navigation">
    <button class="slider-button slider-button-prev"></button>
    <button class="slider-button slider-button-next"></button>
  </div>

  <div class="slider-pagination">
    <button class="slider-dot"></button>
    <button class="slider-dot"></button>
    <button class="slider-dot"></button>
  </div>
</div>
```

2021-10-01 11:26 UTC, davletbaev commented on catalog.html
> +                        <a href="#">
Можно сделать через css, но тебе надо как-то через разметку передавать информацию о том, что здесь должен быть значок NEW. Это можно сделать, например, классом `is-new`. Кстати, у тебя здесь в названии класса ошибка. Должно быть car**d**, а не car**t** (cart - тележка, card - карточка).

2021-10-01 11:28 UTC, davletbaev commented on catalog.html
> +                    <button class="range-button min-range" type="button">
Не нужно img здесь использовать :)
Можно просто через div или span.

2021-10-01 11:29 UTC, davletbaev commented on catalog.html
> +                                <input type="checkbox" name="black" checked>
Ты поняла правильно.
Чтобы при нажатии иконки активировался нужный инпут, ты это все оборачиваешь в label.

2021-10-01 11:34 UTC, davletbaev commented on index.html
> +                <h3>Доставка</h3>
Ссылка на #delivery и блок с id "delivery" позволяют сделать анкорную ссылку на блок на странице. 
Этот блок можно сделать вообще без js. Если использовать css селектор :target.
https://developer.mozilla.org/ru/docs/Web/CSS/:target

Если js не будет на странице, то этот блок все равно будет работать.

2021-10-01 19:23 UTC, lolipopaa commented on index.html
> +                <h3>Доставка</h3>
я не буду скрывать, я нифига не поняла))
при использовании target я буду же ссылаться на id, а это вроде по критериям не стоит делать
или тут какое то исключение?
и я все равно не понимаю, а как они будут переключаться с таргетом?

а мы можем сделать как со слайдером? типо будут кнопки "доставка", "кредит", "гарантия", а остальное будет переключаться?

2021-10-01 19:43 UTC, lolipopaa commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
ну вот, что вышло, но мне кажется что-то не то


<div class="range">
                        <label>
                            <span class="visualy-hidden">
                                Изменить минимальную цену
                            </span>
                            от <input class="catalog-filter-input visualy-hidden" type="number" name="min-price">
                        </label>

                        <label>
                            <span class="visualy-hidden">
                                Изменить максимальную цену
                            </span>
                            до <input class="catalog-filter-input visualy-hidden" type="number" name="max-price">
                        </label>
                    </div>

2021-10-01 19:44 UTC, lolipopaa commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
ну вот, что вышло, но мне кажется что-то не то

<div class="range">
                        <label>
                            <span class="visualy-hidden">
                                Изменить минимальную цену
                            </span>
                            от <input class="catalog-filter-input visualy-hidden" type="number" name="min-price">
                        </label>

                        <label>
                            <span class="visualy-hidden">
                                Изменить максимальную цену
                            </span>
                            до <input class="catalog-filter-input visualy-hidden" type="number" name="max-price">
                        </label>
                    </div>

2021-10-01 19:44 UTC, lolipopaa commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
<div class="range">
                        <label>
                            <span class="visualy-hidden">
                                Изменить минимальную цену
                            </span>
                            от <input class="catalog-filter-input visualy-hidden" type="number" name="min-price">
                        </label>

                        <label>
                            <span class="visualy-hidden">
                                Изменить максимальную цену
                            </span>
                            до <input class="catalog-filter-input visualy-hidden" type="number" name="max-price">
                        </label>
                    </div>

2021-10-01 19:45 UTC, lolipopaa commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
```
<div class="range">
                        <label>
                            <span class="visualy-hidden">
                                Изменить минимальную цену
                            </span>
                            от <input class="catalog-filter-input visualy-hidden" type="number" name="min-price">
                        </label>

                        <label>
                            <span class="visualy-hidden">
                                Изменить максимальную цену
                            </span>
                            до <input class="catalog-filter-input visualy-hidden" type="number" name="max-price">
                        </label>
                    </div>
```

2021-10-01 19:46 UTC, lolipopaa commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
вот что у меня вышло, но мне кажется, что что-то где-то не так

2021-10-01 19:58 UTC, lolipopaa commented on catalog.html
> +                        <a href="#">
<div class="product-card">
                                <img src="" alt="">
                                <span class="is-new"></span>
                                <h3>Селфи-палка «Следуй за мной»</h3>
                            <span class="product-cart-price">4900 ₽</span>
                        </div>

2021-10-01 19:58 UTC, lolipopaa commented on catalog.html
> +                        <a href="#">
`<div class="product-card">
                                <img src="" alt="">
                                <span class="is-new"></span>
                                <h3>Селфи-палка «Следуй за мной»</h3>
                            <span class="product-cart-price">4900 ₽</span>
                        </div>`

2021-10-01 19:59 UTC, lolipopaa commented on catalog.html
> +                        <a href="#">
ну вот я добавляю спан с классом для новых товаров
а у остальных я его же тоже прописываю, т.е. span class="is-new vissualy-hidden", так?)

2021-10-03 12:50 UTC, davletbaev requested changes

2021-10-03 12:50 UTC, davletbaev commented on catalog.html
> +                        от <input class="catalog-filter-input" type="number" name="min-price">
Да, слишком сложная структура получается.
Вообще будет достаточно такого:
```html
<div class="range">
  <label for="priceMin">от 0</label>
  <input id="priceMin" type="range" min="0" step="1" max="10000" value="0">

  <label for="priceMax">до 5000</label>
  <input id="priceMax" type="range" min="0" step="1" max="10000" value="5000">
</div>
```
Можно даже инпут не скрывать, остальное все делается через css и js
https://ru.stackoverflow.com/a/1025380

2021-10-03 12:50 UTC, davletbaev commented on catalog.html
> +                        <a href="#">
Нет, спан не нужен, просто на одну из карточек добавь этот класс, чтобы в будущем не забыть для него сделать значок NEW через псевдоэлемент.

2021-10-03 12:50 UTC, davletbaev commented on index.html
> +                <h3>Доставка</h3>
В критериях про это ничего нет)
Реализовать можешь разными вариантами. Либо как я предложил. Либо с кнопками и переключать чисто из JS. Но в любом случае тебе надо блок с навигацией, в котором будет 3 кнопки, и большой блок с тремя блоками информации.

2021-10-04 00:31 UTC, davletbaev requested changes
Не все комментарии были исправлены с прошлого раза. 
Особенно обрати внимание на футер. Тебе будет сложно потом правильно спозиционировать блоки при текущей разметке. Заголовки и группировка по логическим блокам в футере как правило являются излишними, так как каждый элемент говорит сам за себя.

2021-10-04 00:31 UTC, davletbaev commented on index.html
> +            <h2 class="visualy-hidden">Наши контакты:</h2>
И еще вопрос, как ты потом планируешь позиционировать адрес с одной стороны, а телефон с другой, если они у тебя в одном блоке, а между ними будет меню?

Лучше будет убрать это разделение на "контакты" и "навигацию". Как и с заголовками, это лишнее.

2021-10-04 00:31 UTC, davletbaev commented on catalog.html
> +        <nav class="navigation">
Зачем здесь два тега nav? хватит одного, в котором будут оба списка.

2021-10-04 00:31 UTC, davletbaev commented on catalog.html
> +                <span class="visualy-hidden">Отсортировать от меньшего к большему</span>
Здесь если ты используешь этот текст как подпись, то логичнее было бы использовать label, а не span

2021-10-04 00:31 UTC, davletbaev commented on catalog.html
> +                    <div class="product-card">
Ссылка должна находиться внутри карточки, а не снаружи, она же является как бы частью этой карточки, а не наоборот.

2021-10-04 00:31 UTC, davletbaev commented on index.html
> +                    Первое предложение
Здесь эти подписи тоже будут лишними. Экранные читалки итак озвучивают номер элемента списка, незачем его дублировать.

2021-10-04 00:31 UTC, davletbaev commented on index.html
> +          <img src="img/htmlacademy.svg" width="115" height="33" alt="Разработано в "HtmlAcademy">
Логотип тоже должен быть ссылкой на сайт Академии

2021-10-04 00:31 UTC, davletbaev commented on index.html
> +              <strong>Порхает как бабочка, жалит как пчела!</strong>
Для правильного позиционирования текста на слайде тебе здесь понабится еще одна обертка.
```html
<article>
  <img src="">
  <div>
    <strong>Порхает как бабочка, жалит как пчела!</strong>
    ...
  </div>
</article>
```

2021-10-05 07:15 UTC, davletbaev approved these changes
Теперь все хорошо. 
Оставил еще пару комментариев, но они не критичные, можешь исправить позже :)

2021-10-05 07:15 UTC, davletbaev commented on catalog.html
> +            <form>
Здесь не нужен тег form. Будет достаточно поля ввода. 
Этот поиск все равно без джаваскрипта работать не будет. 
Если на сайте есть отдельная страница с поиском, то можно было бы подстраховаться, и добавить ссылку на нее, при отключенном JS. Но опять же, мы не знаем, есть ли эта страница в данном случае, на современных сайтах их редко делают.

2021-10-05 07:15 UTC, davletbaev commented on catalog.html
> +                    <div class="product-card pointed">
Класс pointed тут не нужен, потому что внешний вид будет меняться по наведению курсора, а не по изменению класса.

2021-10-05 07:16 UTC, merged

2021-10-05 07:35 UTC, davletbaev commented on catalog.html
> +            <form>
Сейчас перепроверил по критериям, что тег form все-таки должен быть. Так что этот момент можешь оставить. Но на будущее имей в виду, что далеко не всегда нужно будет писать именно так :)