Декоративные элементы на главной странице
htmlacademy-htmlcss/1793357-device-32 pull request #7
Opened 2021-11-06 14:10 UTC by lolipopaa

2021-11-07 11:29 UTC, davletbaev requested changes
Привет, по поводу не отображаемых иконок: я погуглил, и все-таки svg-спрайты через css использовать нельзя. Так что тут два варианта. 
1) Создавать для иконки отдельный span. 
2) В css использовать отдельные иконки.
Сейчас рекомендую остановиться на втором.

2021-11-07 11:29 UTC, davletbaev commented on index.html
> +                    <use href="/img/icons-sprite.svg#login"></use>
У тебя здесь и в нескольких других местах используются абсолютные пути. В опубликованной версии из-за этого эти иконки не отображаются

2021-11-07 11:29 UTC, davletbaev commented on index.html
>            <div class="slider-navigation">
Здесь тебе лучше позиционировать не отдельные кнопки, а сам контейнер с кнопками.

2021-11-07 11:29 UTC, davletbaev commented on index.html
> +            <li class="services-item buttons-container">
Здесь у тебя визуально не меняется активный элемент,

2021-11-07 11:29 UTC, davletbaev commented on css/styles.css
>  .delivery-icon::after{
эту картинку лучше позиционировать абсолютно, потому что это просто фон, она не должна влиять на остальную разметку

2021-11-07 11:29 UTC, davletbaev commented on css/styles.css
>  .delivery-link::before{
У этой иконки у тебя откуда появился ненужный отступ снизу
<img width="305" alt="Снимок экрана 2021-11-07 в 14 24 24" src="https://user-images.githubusercontent.com/25131400/140642919-5383719f-9348-4a12-8b51-2cb7e7f3b92b.png">

2021-11-07 11:29 UTC, davletbaev commented on css/styles.css
У списка в разделе About us, маркеры списка не выровнены относительно текста
<img width="194" alt="Снимок экрана 2021-11-07 в 14 23 57" src="https://user-images.githubusercontent.com/25131400/140642906-7542525b-6182-4575-87c5-f40433a3f39a.png">

2021-11-07 11:29 UTC, davletbaev commented on index.html
>             <h2 class="visually-hidden">Мы в социальных сетях.</h2>
Этот элемент тоже должен быть выровнен относительно середины кнопок соцсетей
<img width="539" alt="Снимок экрана 2021-11-07 в 14 26 54" src="https://user-images.githubusercontent.com/25131400/140642992-8e756c56-ca3d-420a-b97a-3e30d908dc71.png">

2021-11-07 15:14 UTC, lolipopaa commented
я почти все исправила, но у меня остались неточности, которые я не знаю, как исправить:
1. элементы в хедере не встают ровно как в макете
2. фокусы у кнопок с желтой фоток не меняют цвет на фиолетовый 
3. у кнопки "показать" в каталоге при наведении не точно встает бэкграунд-колор
подскажи пожалуйста, как это исправить?

2021-11-07 15:15 UTC, lolipopaa commented on index.html
> +            <li class="services-item buttons-container">
так а он должен меняться? я не увидела это в стайлгайде

2021-11-08 06:09 UTC, davletbaev commented on index.html
> +            <li class="services-item buttons-container">
Должен
![image](https://user-images.githubusercontent.com/25131400/140692502-6718c024-8074-4629-bd54-45ab4de88231.png)

2021-11-08 06:54 UTC, davletbaev requested changes
Ты зачем-то стала везде использовать отрицательные отступы. Так делать не надо.
Они нужны только в единичных случаях. Так что старайся использовать их по-минимуму. Они не должны быть на каждом втором элементе.

Пользуйся инструментами разработчика, чтобы понять, где у тебя ошибка. Большинство твоих вопросов решается просто тем, чтобы открыть опубликованную версию и посмотреть через инструменты разработчика на элемент. 

Перепроверь элементы на соответствие стайлгайду, много где некорректно отображаются состояния, особенно фокусы. Для фокусов используй селектор :focus-visible, вместо :focus. А еще у тебя при фокусе элементы скачут, используй хитрости с прозрачной границей или с box-shadow, о которых я тебе говорил на консультации.

А еще на странице каталога в футере у тебя логотип Академии черного цвета, вместо желтого.

2021-11-08 18:41 UTC, lolipopaa commented
:focus-visible использовать не стала, тк он не проходит по критериям (не поддерживается в safari)

2021-11-09 06:11 UTC, davletbaev requested changes
1. Здесь кнопка слишком широка и заезжает на соседнюю. Сверь со стайлгайдом.
<img width="661" alt="Снимок экрана 2021-11-09 в 08 50 55" src="https://user-images.githubusercontent.com/25131400/140869830-5af4b9e0-6972-4e49-ac45-bc97c0957987.png">

2. Здесь кнопка и иконка должны стоять рядом, но не пересекаться. Сверь со стайлгайдом.
<img width="430" alt="Снимок экрана 2021-11-09 в 08 51 39" src="https://user-images.githubusercontent.com/25131400/140869900-6b0ea726-18ee-42d2-9636-a4c9a4e0ed5d.png">

3. Кнопки слайдера скачут при фокусе, цвет обводки при фокусе не соответствует стайлгайду
<img width="165" alt="Снимок экрана 2021-11-09 в 08 52 56" src="https://user-images.githubusercontent.com/25131400/140870018-d50dc00e-2e69-4415-a1f0-d874715ece6d.png">

4. У тебя фон относится к кнопке, он не должен находиться вне ее и уже тем более не должно быть классов, относящихся к кнопке на элементе li. Если ты скопируешь эту кнопку отсюда и вставишь в другое место, у тебя должно все работать, а сейчас у тебя все сломается. То же самое со всеми остальными кнопками. 
Черный же фон относится больше не к конкретной кнопке, а к навигации этого блока, поэтому его можно прилепить к li. И он должен появляться только если есть класс selected. В стайлгайде написано "Активность", но это не селектор :active, :active - это нажатие🤷🏻‍♂️

<img width="546" alt="Снимок экрана 2021-11-09 в 08 57 06" src="https://user-images.githubusercontent.com/25131400/140870385-171cabc2-5ef0-4dc1-a2e3-9242f2a24531.png">

5. Эта ссылка соответствует ссылке из подвала. Можно использовать ее стайлгайд;
<img width="294" alt="Снимок экрана 2021-11-09 в 09 02 19" src="https://user-images.githubusercontent.com/25131400/140870915-f35e1c03-77c2-41da-8d5f-9c191a19bf70.png">
 
 6. В футере на всех элементах осталась дефолтная рамка для фокуса в дополнение к той, что добавила ты.
<img width="1362" alt="Снимок экрана 2021-11-09 в 09 03 58" src="https://user-images.githubusercontent.com/25131400/140871063-7a8605b3-0f9b-408b-9b2d-5944c27e7a86.png">

7. У тебя здесь проблема опять же потому, что ты зачем-то вынесла элементы относящиеся к кнопке за ее пределы. Такого не должно быть.
<img width="291" alt="Снимок экрана 2021-11-09 в 09 05 37" src="https://user-images.githubusercontent.com/25131400/140871200-214db1e7-528a-471d-9691-ab020c4ecc1e.png">

8. Здесь тоже при навигации с клавиатуры видна стандартная рамка фокуса
<img width="521" alt="Снимок экрана 2021-11-09 в 09 07 00" src="https://user-images.githubusercontent.com/25131400/140871314-4699535f-fe67-407f-a554-51b659f96395.png">

9. Здесь ты зачем-то пытаешься сделать картинку прозрачной и задать ей фон.
Если обратишь внимание, то в макете полупрозачный фон наложен поверх картинки.
Так что тебе его надо задавать для before. 
А еще при фокусе карточки у тебя картинка "ужимается" из-за появляющейся границы.
<img width="415" alt="Снимок экрана 2021-11-09 в 09 08 19" src="https://user-images.githubusercontent.com/25131400/140871447-1cf1cd27-cf94-4ffc-a262-b9f028b0048e.png">
<img width="429" alt="Снимок экрана 2021-11-09 в 09 10 20" src="https://user-images.githubusercontent.com/25131400/140871651-3a3ffb93-cc2c-4b39-b971-bcb26b784a59.png">

2021-11-09 18:52 UTC, lolipopaa commented
1. я не понимаю, как мне ограничить фокус у элемента в хедере, если там стоит flex-grow (кнопка "Войти")
2. я сделала у focus{padding}, но тогда вылетает плюсик (элемент catalog-link;before)
3. касательно кнопок я не понимаю. у меня же был класс .selected у li и были описаны в этом selected кнопки. почему это неправильно?
4. кнопки я переделала. посмотри пожалуйста, правильно ли выходит

2021-11-09 20:44 UTC, lolipopaa commented
я вроде бы все исправила
если будут замечания, то напиши, пожалуйста, на что обратить внимание при исправлении
а то я вроде бы исправляю, но тяжело соображаю почему все равно косяк выходит

2021-11-10 08:23 UTC, davletbaev requested changes
1. Здесь иконка светлее чем обводка, а должна быть тоже черной
<img width="186" alt="Снимок экрана 2021-11-10 в 11 01 49" src="https://user-images.githubusercontent.com/25131400/141073519-faf144a0-7c88-4798-a2cf-2b2d67b6aad1.png">

2. Здесь от текста до подчеркивания расстояние должно быть чуть больше. И отступы справа и слева, по-моему, разные
<img width="201" alt="Снимок экрана 2021-11-10 в 11 02 34" src="https://user-images.githubusercontent.com/25131400/141073612-dc6c50b7-056f-4f08-9e08-b4ebee08452e.png">

3. Кнопки так и не исправила
<img width="287" alt="Снимок экрана 2021-11-10 в 11 04 09" src="https://user-images.githubusercontent.com/25131400/141073837-07f8d388-24e3-46b3-a27e-b1b25e7995c2.png">

Сама кнопка должна иметь такие размеры, а не ее родитель. Нельзя задавать ей состояние через родителя, если только это не состояние специфичное для конкретного родителя. И то лучше сделать для этого отдельный модификатор для самой кнопки. В любом случае, у тебя здесь просто кнопка и все ее стили должны быть внутри нее и относится именно к ее классам. Тебе надо стилизовать именно элемент button, либо a, если это ссылка.
<img width="199" alt="Снимок экрана 2021-11-10 в 11 04 59" src="https://user-images.githubusercontent.com/25131400/141073987-5c3d234f-a8a7-4482-b87d-0ed5b83e6de6.png">

4. Забудь про селектор :focus-within, в этом проекте нет случаев, когда его нужно было бы использовать.

5. Попробуй пройтись по всем элементам с помощью tab. На всех элементах сохраняется дефолтная браузерная обводка, ее нужно обнулять, раз ты назначаешь свои стили на состояние фокуса.

6. А еще в разных местах у тебя кнопки выглядят по разному. Хотя по стайлгайду у тебя там всего 2 варианта  —  c высотой 40px и 50px. Ширина же регулируется на уровне родителя кнопки, мы это обсуждали на консультации.
<img width="351" alt="Снимок экрана 2021-11-10 в 11 11 51" src="https://user-images.githubusercontent.com/25131400/141074910-45b91427-ad0d-4ead-8918-8a4ac0790951.png">
 
7. При фокусе логотипа появляется ненужный отступ снизу. Попробуй задать элементу svg внутри ссылки `display: block`
<img width="255" alt="Снимок экрана 2021-11-10 в 11 14 13" src="https://user-images.githubusercontent.com/25131400/141075264-e2609c91-16a6-4bc7-93bf-b8fdf635566c.png">

8. Здесь тоже отступы не соответствуют стайлгайду
<img width="134" alt="Снимок экрана 2021-11-10 в 11 16 41" src="https://user-images.githubusercontent.com/25131400/141075583-f256e496-e3d3-4de8-84e5-40e01bdb7be4.png">

2021-11-10 16:51 UTC, lolipopaa commented
я все еще раз поправила, но забыла про +- в кнопке "каталог"
она у меня нормально отображается
с чем может быть проблема в ней?

2021-11-11 06:38 UTC, davletbaev requested changes
Привет, уже намного лучше👍🏻
Это последние комментарии:

1. Почему-то здесь при фокусе у тебя все равно стили идут по селектору от родителя. К тому же на этой кнопке фокус ведет себя немного иначе, чем на кнопке в слайдере, например.<img width="445" alt="Снимок экрана 2021-11-11 в 09 28 25" src="https://user-images.githubusercontent.com/25131400/141248875-21ece235-e7e1-48fc-9b12-0e92b325d580.png">
Я думаю, правильнее будет, чтобы состояния по наведению и по фокусу, не накладывались друг на друга.<img width="445" alt="Снимок экрана 2021-11-11 в 09 30 01" src="https://user-images.githubusercontent.com/25131400/141249061-b7ec3a72-af61-4a3c-8c27-bfc13f9d4dfd.png">

2. Иконка плюса у тебя светлее потому что на ней есть прозрачность, в самой иконке, ее можно оттуда убрать.

3. Неактивные слайды надо прятать через `display: none`, а не через `visually-hidden`. Иначе на них перескакивает фокус, при навигации с клавиатуры. Такого не должно быть.
<img width="427" alt="Снимок экрана 2021-11-11 в 09 33 59" src="https://user-images.githubusercontent.com/25131400/141249501-353b4d1e-9321-43c0-9a5c-ec17de15d37d.png">

2021-11-12 08:27 UTC, davletbaev requested changes
1. Не исправила косяк с полупрозрачной иконкой у кнопки каталога
2. С кнопками в разделе услуг у тебя все равно что-то не то. Во-первых, первая кнопка у тебя не отцентрирована, как остальные. Во-вторых, я тебе говорил, что состояние выбранного элемента нужно цеплять не к кнопке, а к элементу li. В-третьих, мы договаривались, что по ширине они меняться не будут, а будет тянуться только псевдоэлемент с черным фоном.
<img width="416" alt="Снимок экрана 2021-11-12 в 11 24 53" src="https://user-images.githubusercontent.com/25131400/141434865-33c6e79d-2faf-472b-89e2-aa80e63bf7cb.png">

2021-11-12 08:27 UTC, davletbaev commented on css/styles.css
> +article:not(.selected-slide){
Селектор по тегу использовать нельзя. У тебя есть класс slide

2021-11-13 11:45 UTC, merged