7.15. Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1793357-device-32 pull request #8
Opened 2021-11-13 16:37 UTC by lolipopaa

2021-11-15 11:35 UTC, davletbaev requested changes
1. Форма поиска вообще не соответствует стайлгайду. Границы кнопки и поля ввода должны накладываться друг на друга, а не быть в 2 ряда. К тому же при появлении кнопки у тебя меняется размер всего элемента. При клике в любое место области внутри рамки должен происходить фокус поля ввода, а сейчас у тебя поле ввода гораздо меньше этой области. Либо сделай label, либо сделай, чтобы input занимал все место. И опять же тебе не надо использовать там focus-within (я же тебе говорил забыть про него)
<img width="583" alt="Снимок экрана 2021-11-15 в 14 22 14" src="https://user-images.githubusercontent.com/25131400/141773600-559b5ce3-a415-42ef-876f-d18b1f6a68b8.png">

2. Вот этот элемент тоже должен показываться по селектору :target, а не по focus-within. Мы же это проговаривали на консультации. Попробуй сама покликать, он по фокусу отображается некорректно.
<img width="487" alt="Снимок экрана 2021-11-15 в 14 26 27" src="https://user-images.githubusercontent.com/25131400/141774194-9b29313a-ac71-401a-98df-65117fb7b595.png">

3. То же самое с кнопкой каталога.

4. По нажатию на эту кнопку не открывается попап
<img width="1253" alt="Снимок экрана 2021-11-15 в 14 28 53" src="https://user-images.githubusercontent.com/25131400/141774523-e83164fc-1f50-4cb6-800e-068f7ac99139.png">

5. Подписи отображаются не совсем корректно. Они должны быть отцентрированы по середине бегунка. К тому же у них нет состояний фокуса и активности.
<img width="286" alt="Снимок экрана 2021-11-15 в 14 31 04" src="https://user-images.githubusercontent.com/25131400/141774809-e6460705-779f-446c-a8ea-6d2d9710ae0f.png">

6. Галочка тоже меняет цвет при фокусе
<img width="228" alt="Снимок экрана 2021-11-15 в 14 32 57" src="https://user-images.githubusercontent.com/25131400/141775048-0181800a-84c4-4b76-a390-b4c9f7bc401f.png">
 
 7. Радиокнопки переключаются как-то странно. Если я нажимаю на радиокнопку, то с нее убирается выделение, а должно быть наоборот.
<img width="293" alt="Снимок экрана 2021-11-15 в 14 33 27" src="https://user-images.githubusercontent.com/25131400/141775112-1f3e2c36-fbc2-4a39-92a8-2debfdba9e5f.png">

8. Эти вообще не работают
<img width="222" alt="Снимок экрана 2021-11-15 в 14 34 22" src="https://user-images.githubusercontent.com/25131400/141775238-d74f543e-6b2a-407e-bcc8-a2973760281a.png">

2021-11-15 15:28 UTC, lolipopaa commented
я не понимаю, правильно ли я сделала попап и у меня не выходит отцентровать как в макете и покрасить при фокусе лейбл с ползунками

2021-11-15 16:53 UTC, davletbaev requested changes
1. Отступ от "пожалуйста, представьтесь" до "что нужно отвезти" слишком маленький. В макете больше.
<img width="854" alt="Снимок экрана 2021-11-15 в 19 41 29" src="https://user-images.githubusercontent.com/25131400/141820038-31b8a881-0253-4730-8418-9fce476c9819.png">

2. Зачем тебе здесь псевдоэлемент в пустом спане? ошибки не стоит делать псевдоэлементами, потому что они обычно меняются из JS
<img width="260" alt="Снимок экрана 2021-11-15 в 19 42 47" src="https://user-images.githubusercontent.com/25131400/141820236-d2b7e0b7-d87f-47bd-884c-5b0c851012c9.png">

3. Эти лейблы не должны быть инпутами. Это просто текст. Зачем тебе кнопки, если у тебя уже есть input с типом range? тут либо полностью кастомный контрол делать на JS, либо использовать полунативное решение. Совместить два этих подхода не выйдет.
Почитай здесь про стилизацию https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
<img width="208" alt="Снимок экрана 2021-11-15 в 19 45 30" src="https://user-images.githubusercontent.com/25131400/141820653-c7a9321e-7d5b-475a-82fe-d9ee71da8938.png">
 
4. Радиокнопки по наведению становятся слишком прозрачными. Проверь по стайлгайду.
<img width="271" alt="Снимок экрана 2021-11-15 в 19 49 11" src="https://user-images.githubusercontent.com/25131400/141821236-50ebd3d8-71e6-45b6-bdf8-0787b95bd0cb.png">

5. Теперь эти кнопки у тебя работают также как в прошлый раз радиокнопки в фильтре. Ты вообще тестируешь верстку сама, перед тем как мне отправлять?)
<img width="152" alt="Снимок экрана 2021-11-15 в 19 49 52" src="https://user-images.githubusercontent.com/25131400/141821347-58ae8622-1aa5-4bd7-92bc-bc1fd6840c2d.png">

6. У поля поиска все еще с размерами беда. Перечитай мой прошлый комментарий по нему. Если в поле введено значение, то у него должна отображаться рамка, и цвет введенного текста меняться не должен
<img width="556" alt="Снимок экрана 2021-11-15 в 19 51 51" src="https://user-images.githubusercontent.com/25131400/141821630-ee15f2d8-7226-4176-b930-44010cb66cfd.png">

2021-11-16 16:51 UTC, lolipopaa commented
я исправила, но у меня все равно остались вопросы:
1. блок с "найти" вылетает. я не могу понять почему
2. я не понимаю, как задать фокус инпутам, тк там целая область и при фокусе выбирается она, а не ползунки
3. я не понимаю, что не так с радиокнопками сортировки
4. ну и нужно уже доделать фон в каталоге, я тоже не секу как его делать
подскажи пожалуйста)

2021-11-16 17:10 UTC, lolipopaa commented
и да, я каждый раз когда делаю, проверяю как все выглядит) если что-то не так работает, это скорее от того, что я не понимаю, как должно быть или как сделать правильно

2021-11-16 18:42 UTC, lolipopaa commented
и у меня еще вопрос: я когда вставляю код для переполнения у меня карточки увеличиваются очень сильно
с чем это может быть связано?

2021-11-16 20:01 UTC, lolipopaa commented
и еще один: в макете в каталоге есть пагинация
там от "назад" и "вперед" неравные отступы до страниц (1,2,3..)
следовательно, я задаю отступ как в макете, но в этом случае у меня не будет проходит критерий переполнения
как это можно исправить или можно оставить как есть?

2021-11-16 20:03 UTC, lolipopaa commented
и еще у меня модалка после того, как я поставила таргет на нее не центрируется по середине окна

2021-11-17 09:58 UTC, davletbaev requested changes
1. Здесь опять что-то с кнопкой доставки, съехала в сторону
<img width="477" alt="Снимок экрана 2021-11-17 в 12 54 22" src="https://user-images.githubusercontent.com/25131400/142178186-6d82930f-9ffd-47b9-aee1-232ccc691ece.png">

2. Состояния фокуса и активности не проработаны
<img width="278" alt="Снимок экрана 2021-11-17 в 12 56 17" src="https://user-images.githubusercontent.com/25131400/142178518-c80b25fe-91a5-4714-bbd0-489e381529e1.png">

3. Стрелки все еще работают наоборот
<img width="192" alt="Снимок экрана 2021-11-17 в 12 56 57" src="https://user-images.githubusercontent.com/25131400/142178645-70fb59eb-cfa6-439b-b77b-b021d050a55f.png">

4. i должна быть черной по стайлгайду
<img width="113" alt="Снимок экрана 2021-11-17 в 12 57 52" src="https://user-images.githubusercontent.com/25131400/142178816-e706ca7e-4a2c-488e-b43d-27cfd2cd079c.png">

2021-11-18 07:38 UTC, davletbaev requested changes
1. При одновременном фокусе и наведении на кнопку "Найти" надпись не видно.
<img width="216" alt="Снимок экрана 2021-11-18 в 10 31 58" src="https://user-images.githubusercontent.com/25131400/142371632-c28db704-3a88-4d68-8aaa-4f77721d4a1d.png">

2. Состояние для empty перетирает состояние ошибки
<img width="1000" alt="Снимок экрана 2021-11-18 в 10 34 46" src="https://user-images.githubusercontent.com/25131400/142372027-173be1ac-7a86-4729-b273-360b9fec8eda.png">

3. Кнопка "Показать" у тебя работает не так кнопки на главной странице. При наведении не должно быть видно состояния фокуса. Форма не отправляется
<img width="341" alt="Снимок экрана 2021-11-18 в 10 37 32" src="https://user-images.githubusercontent.com/25131400/142372396-9023bb56-2d15-41b8-a810-36894b609ece.png">

2021-11-18 18:51 UTC, lolipopaa commented
я исправила почти все, но у меня не выходит переполнение в каталоге
оно выпадает полностью и я не понимаю, как его исправить

2021-11-18 19:04 UTC, lolipopaa commented
<img width="598" alt="Снимок экрана 2021-11-18 в 22 03 19" src="https://user-images.githubusercontent.com/90265637/142480049-002ba243-d7a2-477b-8273-c205963f82fc.png">

и еще вопрос: я добавляю переполнение, а у меня такая фигня с кнопкой
значит ли это, что ее нужно как то тянуть или ограничивать, чтобы такого не было? если да, то как это сделать?

2021-11-18 20:10 UTC, merged